# Generated by Django 5.2 on 2025-06-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_original', models.TextField()),
                ('mensaje_anonimo_y_constructivo', models.TextField(blank=True, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
